-- Shadow-Blockplanner Relational Database Schema
-- Target: PostgreSQL 14+


-- 1. Track Management System (Engineering Dept)
CREATE TABLE IF NOT EXISTS tms_track_defects (
    defect_id VARCHAR(30) PRIMARY KEY,
    gq_corridor VARCHAR(50) NOT NULL,
    railway_zone VARCHAR(20) NOT NULL,
    block_section VARCHAR(50) NOT NULL,
    track_km NUMERIC(7,2) NOT NULL,
    defect_type VARCHAR(60) NOT NULL,
    urgency_level VARCHAR(15) NOT NULL,
    ambient_temp_c NUMERIC(4,1) NOT NULL,
    required_block_hours NUMERIC(3,1) NOT NULL,
    logged_timestamp TIMESTAMP NOT NULL
);

-- 2. Signalling Maintenance & Management System (Signal Dept)
CREATE TABLE IF NOT EXISTS smms_signal_defects (
    defect_id VARCHAR(30) PRIMARY KEY,
    gq_corridor VARCHAR(50) NOT NULL,
    station_code VARCHAR(10) NOT NULL,
    asset_type VARCHAR(50) NOT NULL,
    failure_mode VARCHAR(60) NOT NULL,
    urgency_level VARCHAR(15) NOT NULL,
    required_block_hours NUMERIC(3,1) NOT NULL,
    logged_timestamp TIMESTAMP NOT NULL
);

-- 3. Traction Distribution Management System (Electrical Dept)
CREATE TABLE IF NOT EXISTS tdms_traction_defects (
    defect_id VARCHAR(30) PRIMARY KEY,
    gq_corridor VARCHAR(50) NOT NULL,
    ohe_sector_id VARCHAR(30) NOT NULL,
    defect_type VARCHAR(60) NOT NULL,
    urgency_level VARCHAR(15) NOT NULL,
    required_block_hours NUMERIC(3,1) NOT NULL,
    logged_timestamp TIMESTAMP NOT NULL
);

-- 4. Control Office Application (Train Timetable & Traffic Forecast)
CREATE TABLE IF NOT EXISTS coa_train_timetable (
    slot_id VARCHAR(30) PRIMARY KEY,
    gq_corridor VARCHAR(50) NOT NULL,
    block_section VARCHAR(50) NOT NULL,
    train_number VARCHAR(20) NOT NULL,
    train_type VARCHAR(30) NOT NULL,
    scheduled_entry TIMESTAMP NOT NULL,
    scheduled_exit TIMESTAMP NOT NULL,
    natural_gap_minutes INT NOT NULL
);

-- 5. Output: Optimized Block Schedules (Generated by OR-Tools)
CREATE TABLE IF NOT EXISTS scheduled_blocks (
    block_plan_id SERIAL PRIMARY KEY,
    gq_corridor VARCHAR(50) NOT NULL,
    block_section VARCHAR(50) NOT NULL,
    primary_department VARCHAR(20) NOT NULL, -- TMS, SMMS, or TDMS
    shadow_departments TEXT[],              -- Combined departments (e.g. ['SMMS', 'TDMS'])
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    duration_hours NUMERIC(3,1) NOT NULL,
    status VARCHAR(20) DEFAULT 'PROPOSED'
);
